import { Elysia, t } from "elysia";
import PDFDocument from "pdfkit";
import { GradingResult } from "@tali/types";

// ── helpers ───────────────────────────────────────────────────────────────

const pct = (score: number, total: number): number =>
  total > 0 ? Math.round((score / total) * 100) : 0;

const scoreGrade = (p: number): string => {
  if (p >= 85) return "Excellent";
  if (p >= 70) return "Good";
  if (p >= 50) return "Average";
  return "Needs Improvement";
};

const buildPdf = (result: GradingResult, locale: "en" | "mr" = "en"): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 48,
      autoFirstPage: true,
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const L = locale === "mr" ? {
      reportTitle: "विद्यार्थी विश्लेषण अहवाल",
      subject: "विषय",
      aiFeedback: "AI अभिप्राय",
      weakAreas: "कमकुवत क्षेत्रे",
      corrections: "प्रश्नवार दुरुस्त्या",
      qNo: "प्र.क्र.",
      marks: "गुण",
      answer: "विद्यार्थ्याचे उत्तर",
      analysis: "विश्लेषण",
      footer: "TALI स्मार्ट ग्रेडिंग प्लॅटफॉर्मद्वारे तयार केले",
    } : {
      reportTitle: "Student Analysis Report",
      subject: "Subject",
      aiFeedback: "AI Feedback",
      weakAreas: "Weak Areas",
      corrections: "Question-wise Corrections",
      qNo: "Q#",
      marks: "Marks",
      answer: "Student Answer",
      analysis: "Analysis",
      footer: "Generated by TALI Smart Grading Platform",
    };

    const W = doc.page.width - 96; // usable width
    const INDIGO = "#4F46E5";
    const DARK = "#1E293B";
    const MID = "#64748B";
    const LIGHT = "#F1F5F9";
    const GREEN = "#10B981";
    const RED = "#EF4444";
    const AMBER = "#F59E0B";

    const score = pct(result.score, result.totalMarks);
    const grade = scoreGrade(score);
    const formattedDate = new Intl.DateTimeFormat("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(new Date(result.date));

    // ── HEADER BAND ───────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(INDIGO);

    doc
      .fillColor("#FFFFFF")
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("TALI", 48, 24);

    doc
      .fillColor("rgba(255,255,255,0.7)")
      .fontSize(9)
      .font("Helvetica")
      .text("Smart Answer Grading Platform", 48, 50);

    doc
      .fillColor("#FFFFFF")
      .fontSize(11)
      .font("Helvetica-Bold")
      .text(L.reportTitle, doc.page.width - 220, 30, {
        width: 180,
        align: "right",
      });

    doc
      .fillColor("rgba(255,255,255,0.7)")
      .fontSize(9)
      .font("Helvetica")
      .text(formattedDate, doc.page.width - 220, 50, {
        width: 180,
        align: "right",
      });

    // ── STUDENT INFO ──────────────────────────────────────────────────────
    let y = 100;

    doc
      .fillColor(DARK)
      .fontSize(20)
      .font("Helvetica-Bold")
      .text(result.studentName, 48, y);

    y += 28;
    doc
      .fillColor(MID)
      .fontSize(11)
      .font("Helvetica")
      .text(`${L.subject}: ${result.subject}`, 48, y);

    // ── SCORE BAND ────────────────────────────────────────────────────────
    y += 30;
    doc.rect(48, y, W, 68).fill(LIGHT).stroke(LIGHT);

    const scoreColor = score >= 70 ? GREEN : score >= 50 ? AMBER : RED;

    doc
      .fillColor(scoreColor)
      .fontSize(32)
      .font("Helvetica-Bold")
      .text(`${score}%`, 60, y + 12);

    doc
      .fillColor(DARK)
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(grade, 60, y + 48);

    doc
      .fillColor(MID)
      .fontSize(10)
      .font("Helvetica")
      .text(`Marks: ${result.score} / ${result.totalMarks}`, 180, y + 20);

    doc
      .fillColor(MID)
      .fontSize(10)
      .font("Helvetica")
      .text(`Questions: ${result.corrections.length}`, 180, y + 38);

    // score bar
    const barX = 320;
    const barW = W - 280;
    doc
      .rect(barX, y + 28, barW, 12)
      .fill("#E2E8F0")
      .stroke("#E2E8F0");
    doc
      .rect(barX, y + 28, (barW * score) / 100, 12)
      .fill(scoreColor)
      .stroke(scoreColor);
    doc
      .fillColor(MID)
      .fontSize(8)
      .text("0%", barX, y + 44)
      .text("100%", barX + barW - 18, y + 44);

    // ── SECTION: AI FEEDBACK ──────────────────────────────────────────────
    y += 90;

    doc
      .fillColor(DARK)
      .fontSize(13)
      .font("Helvetica-Bold")
      .text(L.aiFeedback, 48, y);

    doc
      .moveTo(48, y + 18)
      .lineTo(48 + W, y + 18)
      .strokeColor("#E2E8F0")
      .lineWidth(1)
      .stroke();

    y += 26;
    const feedbackHeight = doc.heightOfString(result.feedback, {
      width: W - 16,
    });
    doc
      .rect(48, y, W, feedbackHeight + 20)
      .fill("#FFFBEB")
      .stroke("#FDE68A");
    doc
      .fillColor("#92400E")
      .fontSize(10)
      .font("Helvetica")
      .text(result.feedback, 56, y + 10, { width: W - 16 });

    y += feedbackHeight + 32;

    // ── SECTION: WEAK AREAS ───────────────────────────────────────────────
    if (result.weakAreas.length > 0) {
      doc
        .fillColor(DARK)
        .fontSize(13)
        .font("Helvetica-Bold")
        .text(L.weakAreas, 48, y);

      doc
        .moveTo(48, y + 18)
        .lineTo(48 + W, y + 18)
        .strokeColor("#E2E8F0")
        .lineWidth(1)
        .stroke();

      y += 26;
      result.weakAreas.forEach((area) => {
        const p2 = Math.max(20, score - 18);
        const bw = W - 140;
        doc.circle(54, y + 5, 3).fill(RED);
        doc
          .fillColor(DARK)
          .fontSize(10)
          .font("Helvetica")
          .text(area, 62, y, { width: 120 });
        doc.rect(200, y, bw, 8).fill("#FEE2E2").stroke("#FEE2E2");
        doc
          .rect(200, y, (bw * p2) / 100, 8)
          .fill(RED)
          .stroke(RED);
        doc
          .fillColor(RED)
          .fontSize(8)
          .font("Helvetica-Bold")
          .text(`${p2}%`, 200 + bw + 6, y);
        y += 20;
      });

      y += 8;
    }

    // ── SECTION: QUESTION CORRECTIONS ─────────────────────────────────────
    if (result.corrections.length > 0) {
      // check if we need a new page
      if (y + 80 > doc.page.height - 60) {
        doc.addPage();
        y = 48;
      }

      doc
        .fillColor(DARK)
        .fontSize(13)
        .font("Helvetica-Bold")
        .text(L.corrections, 48, y);

      doc
        .moveTo(48, y + 18)
        .lineTo(48 + W, y + 18)
        .strokeColor("#E2E8F0")
        .lineWidth(1)
        .stroke();

      y += 26;

      // Table header
      const cols = { q: 48, marks: 110, answer: 165, analysis: 340 };
      doc.rect(48, y, W, 18).fill(INDIGO).stroke(INDIGO);
      doc
        .fillColor("#FFFFFF")
        .fontSize(8)
        .font("Helvetica-Bold")
        .text(L.qNo, cols.q + 4, y + 5)
        .text(L.marks, cols.marks + 4, y + 5)
        .text(L.answer, cols.answer + 4, y + 5)
        .text(L.analysis, cols.analysis + 4, y + 5);

      y += 18;

      result.corrections.forEach((c, idx) => {
        const isGood = c.marksObtained >= c.maxMarks * 0.6;
        const rowColor = idx % 2 === 0 ? "#FFFFFF" : "#F8FAFC";
        const rowH = Math.max(
          28,
          doc.heightOfString(c.studentAnswer.substring(0, 60), {
            width: 160,
          }) +
            doc.heightOfString(c.analysis.substring(0, 80), {
              width: 180,
            }) +
            12,
        );

        if (y + rowH > doc.page.height - 80) {
          doc.addPage();
          y = 48;
          // re-draw header
          doc.rect(48, y, W, 18).fill(INDIGO).stroke(INDIGO);
          doc
            .fillColor("#FFFFFF")
            .fontSize(8)
            .font("Helvetica-Bold")
            .text(L.qNo, cols.q + 4, y + 5)
            .text(L.marks, cols.marks + 4, y + 5)
            .text(L.answer, cols.answer + 4, y + 5)
            .text(L.analysis, cols.analysis + 4, y + 5);
          y += 18;
        }

        doc
          .rect(48, y, W, rowH)
          .fill(rowColor)
          .strokeColor("#E2E8F0")
          .lineWidth(0.5)
          .stroke();

        doc
          .fillColor(DARK)
          .fontSize(9)
          .font("Helvetica-Bold")
          .text(`Q${c.questionNo}`, cols.q + 4, y + 8);

        doc
          .fillColor(isGood ? GREEN : RED)
          .fontSize(9)
          .font("Helvetica-Bold")
          .text(`${c.marksObtained}/${c.maxMarks}`, cols.marks + 4, y + 8);

        doc
          .fillColor(DARK)
          .fontSize(8)
          .font("Helvetica")
          .text(c.studentAnswer.substring(0, 120), cols.answer + 4, y + 6, {
            width: 165,
          });

        doc
          .fillColor(MID)
          .fontSize(8)
          .font("Helvetica")
          .text(c.analysis.substring(0, 160), cols.analysis + 4, y + 6, {
            width: W - 298,
          });

        y += rowH;
      });
    }

    // ── FOOTER ─────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 40;
    doc
      .moveTo(48, footerY)
      .lineTo(doc.page.width - 48, footerY)
      .strokeColor("#E2E8F0")
      .lineWidth(1)
      .stroke();

    doc
      .fillColor(MID)
      .fontSize(8)
      .font("Helvetica")
      .text(
        `${L.footer}  ·  ${formattedDate}`,
        48,
        footerY + 8,
        { width: W, align: "center" },
      );

    doc.end();
  });

// ── Route ─────────────────────────────────────────────────────────────────

export const reportsRoutes = new Elysia({ prefix: "/api/reports" }).post(
  "/pdf",
  async ({ body, set }) => {
    try {
      const result = body.result as unknown as GradingResult;
      const locale = (body.locale as "en" | "mr") ?? "en";
      const buffer = await buildPdf(result, locale);

      set.headers["Content-Type"] = "application/pdf";
      set.headers["Content-Disposition"] =
        `attachment; filename="${encodeURIComponent(result.studentName)}_report.pdf"`;
      set.headers["Content-Length"] = String(buffer.length);

      return buffer;
    } catch (error) {
      set.status = 500;
      return {
        error: error instanceof Error ? error.message : "PDF generation failed",
      };
    }
  },
  {
    auth: true,
    body: t.Object({
      result: t.Record(t.String(), t.Unknown()),
      locale: t.Optional(t.Union([t.Literal("en"), t.Literal("mr")])),
    }),
  },
);
